apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.60.3-apline
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTS
          value: -Xmx2048m -Djava.util.logging.config.file=/var/jenkins_home/log.properties
        ports:
        - name: http-port
          containerPort: 8080
        - name: discovery-port
          containerPort: 50000
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins
      volumes:
        - name: jenkins
          persistentVolumeClaim:
            claimName: jenkins-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
    name: ui
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-discovery
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
  - port: 50000
    targetPort: 50000
    protocol: TCP
    name: slaves