apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    type: local
spec:
  storageClassName: namual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  capacity:
    storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  storageClassName: namual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi